### PR TITLE
In my Module E220-400T30D fix Save mode returned not recognized!

### PR DESCRIPTION
**Pull request by AntonioPrevitali**
Evaluate whether it is okay to implement this change.
Also because it seems error in datascheet!
Yet my module works like this!

### CODE REVIEW

**Comment by xreef** [comment]
Thanks, Antonio,
I am writing to EByte to solve this question.
I will write here when I receive a response.
Bye Renzo

**Comment by AntonioPrevitali** [comment]
ho fatto un altra piccola variazione che mi permetto di sottoporle.

Vedi variazioni e commenti in [6613cee] Update Lora_E220.cpp

**Comment by xreef** [comment]
Hi Antonio,
EBayte answers me, and It says that It's impossible.
I also do some tests with my modules, and they work correctly.

They ask me for a video with the problem, if you have a logic analyzer or other, you can try to do that.

Bye Renzo

**Comment by AntonioPrevitali** [comment]
Hi Renzo
in the meantime there was an answer from Ebyte.
I've come to the conclusion that something very strange is going on with the softserial.
In fact if I use serial hardware everything is ok.
I did not investigate as C0 arrived instead of C1
However, it is evident that it is not the Ebyte module.
Since I solved (using hardwareserial) I close the pull request. do not implement the suggested change.

Grazie.

**Comment by xreef** [comment]
Ok, anyway, thanks for the support.
Bye Renzo

**Pull request closed without merging**
